theme = "tokyonight_moon"

[editor]
line-number = "relative"
true-color = true
mouse = false
cursorline = true
completion-trigger-len = 1
cursorcolumn = true
continue-comments = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = ":config-reload"
H = ":buffer-previous"
L = ":buffer-next"
# A-w = ":buffer-close"
"C-/" = "toggle_comments"
